# Generated by Django 5.2.4 on 2025-07-21 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_number', models.CharField(max_length=10, unique=True)),
                ('space_type', models.CharField(choices=[('room', 'Room'), ('hall', 'Hall')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='space_images/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('booking_code', models.CharField(blank=True, max_length=20, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(blank=True, limit_choices_to={'space_type': 'room'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to='bookings.space')),
            ],
            options={
                'verbose_name': 'Room Booking',
                'verbose_name_plural': 'Room Bookings',
            },
        ),
        migrations.CreateModel(
            name='HallBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('booking_code', models.CharField(blank=True, max_length=20, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_bookings', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(blank=True, limit_choices_to={'space_type': 'hall'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hall_bookings', to='bookings.space')),
            ],
            options={
                'verbose_name': 'Hall Booking',
                'verbose_name_plural': 'Hall Bookings',
            },
        ),
    ]
