# Generated by Django 5.2.1 on 2025-07-14 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('room', 'Room'), ('hall', 'Hall')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='roombooking',
            options={'ordering': ['-booked_at']},
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='special_requests',
        ),
        migrations.AddField(
            model_name='roombooking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='booking_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='HallBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('booking_code', models.CharField(blank=True, max_length=20, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_bookings', to=settings.AUTH_USER_MODEL)),
                ('hall', models.ForeignKey(blank=True, limit_choices_to={'room_type': 'hall'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hall_bookings', to='bookings.room')),
            ],
            options={
                'ordering': ['-booked_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='roombooking',
            name='room',
            field=models.ForeignKey(blank=True, limit_choices_to={'room_type': 'room'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to='bookings.room'),
        ),
        migrations.DeleteModel(
            name='EventBooking',
        ),
    ]
