# Generated by Django 5.2.1 on 2025-07-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_room_alter_roombooking_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('space_type', models.CharField(choices=[('room', 'Room'), ('hall', 'Hall')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='space_images/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='hallbooking',
            name='hall',
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='space',
            field=models.ForeignKey(blank=True, limit_choices_to={'space_type': 'hall'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hall_bookings', to='bookings.space'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='space',
            field=models.ForeignKey(blank=True, limit_choices_to={'space_type': 'room'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to='bookings.space'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
