# Generated by Django 5.2.1 on 2025-07-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_space_remove_roombooking_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='room_number',
            new_name='space_number',
        ),
    ]
